#db tk gg vuutruongnhatthanh@gmail.com
spring.application.name=backend
spring.mongodb.uri=mongodb+srv://admin:Vuutruong99++@cluster0.5mvoiyd.mongodb.net/expensetracker?retryWrites=true&w=majority
server.port=8080